---
kind: pipeline
type: docker
name: backend
   
steps:
- name: test
  image: alpine
  commands:
  - cat test.txt
  - whoami
  when:
    event:
      exclude:
        - promote

- name: build
  privledged: true
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - "docker build -t backend:${DRONE_BUILD_NUMBER} ."
  when:
    ref:
      include:
        - refs/tags/*
    event:
      exclude:
        - promote

- name: deploy
  image: alpine
  commands:
    - echo "Deployment placeholder"
    - echo "Deploy ${DRONE_TAG} to production."
  when:
    ref:
      include:
        - refs/tags/*
    event:
      - promote
    target:
      - production

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
