kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - cat test.txt
  - whoami

- name: build
  image: docker
  commands:
    - docker build -t test:${DRONE_BUILD_NUMBER} .
