kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: alpine
  commands:
  - cat test.txt
  - whoami

- name: build
  privledged: true
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - "docker build -t test:${DRONE_BUILD_NUMBER} ."

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
